version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=eventdb
      - DB_USER=eventuser
      - DB_PASSWORD=eventpass
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

