apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-web-app
  namespace: event-web-app
spec:
  replicas: 2  # Reduced since it's static
  selector:
    matchLabels:
      app: event-web-app
  template:
    metadata:
      labels:
        app: event-web-app
    spec:
      containers:
      - name: flask-app
        image: sahil214/event-web-app:v1  # Updated image without DB code
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "200m"  # Reduced resources
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health  # Now exists!
            port: 5000
          initialDelaySeconds: 10