apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-web-app
  labels:
    app: event-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-web-app
  template:
    metadata:
      labels:
        app: event-web-app
    spec:
      containers:
      - name: event-web-app
        image: sahil214/event-web-app:latest
        ports:
        - containerPort: 5000
