apiVersion: v1
kind: Service
metadata:
  name: event-web-app-service
  labels:
    app: event-web-app
spec:
  type: ClusterIP  # Internal service (default)
  ports:
    - name: http
      port: 80
      targetPort: 5000  # Matches your Flask app's port
  selector:
    app: event-web-app  # Must match deployment labels
