apiVersion: v1
kind: Service
metadata:
  name: eventwebapp-service
  namespace: event-web-app
spec:
  type: NodePort
  selector:
    app: event-web-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080