apiVersion: v1
kind: Service
metadata:
  name: eventwebapp-service
spec:
  type: NodePort        # Exposes the service on a specific node port
  selector:
    app: eventwebapp    # Selects the pods with the "app: eventwebapp" label
  ports:
    - protocol: TCP
      port: 80          # Exposes port 80 on the service
      targetPort: 5000   # Forwards traffic to port 5000 in the container
      nodePort: 30080    # Exposes the service on port 30080 on every node
